# Generated by Django 3.1.7 on 2021-03-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitenpromotion',
            name='newprice',
            field=models.FloatField(default=0),
        ),
    ]
